services:
  - type: web
    name: flask-csv-cleaner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    runtime: python
    region: oregon  # Or any region you prefer
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
